/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/atoms/Background.vue')['default']
    Badges: typeof import('./src/components/atoms/Badges.vue')['default']
    Button: typeof import('./src/components/atoms/Button.vue')['default']
    Chips: typeof import('./src/components/atoms/Chips.vue')['default']
    FooterTemplate: typeof import('./src/components/templates/FooterTemplate.vue')['default']
    HeaderTemplate: typeof import('./src/components/templates/HeaderTemplate.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Image: typeof import('./src/components/atoms/Image.vue')['default']
    Input: typeof import('./src/components/atoms/Input.vue')['default']
    LoginBox: typeof import('./src/components/molecules/LoginBox.vue')['default']
    LoginPage: typeof import('./src/components/pages/LoginPage.vue')['default']
    LoginTemplate: typeof import('./src/components/templates/LoginTemplate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBarTemplate: typeof import('./src/components/templates/SideBarTemplate.vue')['default']
    Template: typeof import('./src/components/templates/Template.vue')['default']
    VBadges: typeof import('./src/components/atoms/VBadges.vue')['default']
    VButton: typeof import('./src/components/atoms/VButton.vue')['default']
    VDialog: typeof import('./src/components/atoms/VDialog.vue')['default']
    Vtemplate: typeof import('./src/components/templates/Vtemplate.vue')['default']
  }
}
