/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiErrorSnackbar: typeof import('./src/components/error/ApiErrorSnackbar.vue')['default']
    Background: typeof import('./src/components/atoms/Background.vue')['default']
    Badges: typeof import('./src/components/atoms/Badges.vue')['default']
    Button: typeof import('./src/components/atoms/Button.vue')['default']
    CategoriesPage: typeof import('./src/components/pages/CategoriesPage.vue')['default']
    CategoryForm: typeof import('./src/components/molecules/CategoryForm.vue')['default']
    CategoryList: typeof import('./src/components/molecules/CategoryList.vue')['default']
    CategoryManagement: typeof import('./src/components/organisms/CategoryManagement.vue')['default']
    Chips: typeof import('./src/components/atoms/Chips.vue')['default']
    DashboardPage: typeof import('./src/components/pages/DashboardPage.vue')['default']
    FinanceDashboard: typeof import('./src/components/organisms/FinanceDashboard.vue')['default']
    FinanceSummaryCard: typeof import('./src/components/molecules/FinanceSummaryCard.vue')['default']
    FooterTemplate: typeof import('./src/components/templates/FooterTemplate.vue')['default']
    HeaderTemplate: typeof import('./src/components/templates/HeaderTemplate.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomePage: typeof import('./src/components/pages/HomePage.vue')['default']
    Image: typeof import('./src/components/atoms/Image.vue')['default']
    Input: typeof import('./src/components/atoms/Input.vue')['default']
    LoginBox: typeof import('./src/components/molecules/LoginBox.vue')['default']
    LoginPage: typeof import('./src/components/pages/LoginPage.vue')['default']
    LoginTemplate: typeof import('./src/components/templates/LoginTemplate.vue')['default']
    Logo: typeof import('./src/components/atoms/Logo.vue')['default']
    RecoveryBox: typeof import('./src/components/molecules/RecoveryBox.vue')['default']
    RecoveryPage: typeof import('./src/components/pages/RecoveryPage.vue')['default']
    RecoveryTemplate: typeof import('./src/components/templates/RecoveryTemplate.vue')['default']
    RegisterBox: typeof import('./src/components/molecules/RegisterBox.vue')['default']
    RegisterPage: typeof import('./src/components/pages/RegisterPage.vue')['default']
    RegisterTemplate: typeof import('./src/components/templates/RegisterTemplate.vue')['default']
    ReportsPage: typeof import('./src/components/pages/ReportsPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBarTemplate: typeof import('./src/components/templates/SideBarTemplate.vue')['default']
    Template: typeof import('./src/components/templates/Template.vue')['default']
    TransactionForm: typeof import('./src/components/molecules/TransactionForm.vue')['default']
    TransactionList: typeof import('./src/components/molecules/TransactionList.vue')['default']
    TransactionManagement: typeof import('./src/components/organisms/TransactionManagement.vue')['default']
    TransactionsPage: typeof import('./src/components/pages/TransactionsPage.vue')['default']
    VBadges: typeof import('./src/components/atoms/VBadges.vue')['default']
    VButton: typeof import('./src/components/atoms/VButton.vue')['default']
    VDialog: typeof import('./src/components/atoms/VDialog.vue')['default']
    Vtemplate: typeof import('./src/components/templates/Vtemplate.vue')['default']
  }
}
